---
language: java
sudo: false
install: true
jdk:
- oraclejdk8
env:
- JOB=H2
- JOB=POSTGRES
- JOB=MYSQL
- JOB=WEB
- JOB=PRANALYSIS
- JOB=ITS_QUALITYGATE
- JOB=ITS_UPDATECENTER
- JOB=ITS_TESTING
matrix:
  fast_finish: true
script:
- "./travis.sh"
cache:
  directories:
  - "$HOME/.m2/repository"
before_cache:
- rm -rf $HOME/.m2/repository/org/codehaus/sonar
