---
language: java
sudo: false
install: true
jdk:
- oraclejdk8
env:
- JOB=H2
- JOB=POSTGRES
- JOB=MYSQL
- JOB=PRANALYSIS
script:
- "./travis.sh"
cache:
  directories:
  - "$HOME/.m2/repository"
before_cache:
- rm -rf $HOME/.m2/repository/org/codehaus/sonar
